[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "quickopts"
version = "0.3.1"
description = "A tiny opinionated Python library for parsing script options."
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"

[tool.setuptools]
package-dir = {"" = "src"}
py-modules = ["quickopts"]
